### ISSUE TITLE
Pagerfanta/View/ViewInterface uses deprecated PagerfantaInterface

### ISSUE THREAD

**Issue by RolfBabijn** [whiteoctober/Pagerfanta#121]
I saw recently that the PagerfantaInterface was deprecated, but the ViewInterface still uses that deprecated interface. Should this be modified too?

Link to the master version of ViewInterface:
https://github.com/whiteoctober/Pagerfanta/blob/master/src/Pagerfanta/View/ViewInterface.php

**Comment by CerebralFart** [comment]
Any idea when Pagerfanta 2.0 will be released
