### ISSUE TITLE
Pager only returns current page when groupBy is set

### ISSUE THREAD

**Issue by juuga** [whiteoctober/Pagerfanta#130]
I have a query which returns all my images with the amount of votes they have.
my_vote has a FK with my_vote.image_id which points to my_image.id.

```
    $queryBuilder = new QueryBuilder($db);
    $queryBuilder
        ->select('i.*', 'u.name', 'COUNT(v.id)')
        ->from('my_image', 'i')
        ->leftJoin('i', 'my_user', 'u', 'i.user_id = u.id')
        ->leftJoin('i', 'my_vote', 'v', 'v.image_id = i.id')
        ->groupBy('i.id')
        ;
```

The SQL looks like this:

```
SELECT i.*, u.name, COUNT(v.id) FROM my_image i LEFT JOIN my_user u ON i.user_id = u.id LEFT JOIN my_vote v ON v.image_id = i.id GROUP BY i.id
```

Unfortunately even though I should have three pages of results, I only get one page. The groupBy seems to be the one causing this. My count modifier looks like this:

```
    $countQueryModifier = function ($queryBuilder) {
        $queryBuilder
            ->select('COUNT(DISTINCT i.id) AS total_results')
            ->setMaxResults(1)
            ;
    };
```

For some reason the groupBy is causing only one page to be shown. I guess the total results amount becomes messed up for some reason.

**Comment by afilina** [comment]
Can confirm that `resetQueryPart('groupBy')` is a pretty solid solution in most cases, but do double-check your results.
