### ISSUE TITLE
Docs error

### ISSUE THREAD

**Issue by skornev** [whiteoctober/Pagerfanta#181]
Options value
- previous_message (Previous) should be prev_message

**Comment by stof** [comment]
Can you send a pull request with the fix ? This would give you attribution on the commit for that fix

**Comment by skornev** [comment]
I have sent a pull request.

**Comment by smoench** [comment]
@skornev @stof documentation has no error.

The Problem was introduced with the `TwitterBootstrapTemplate`. The BootstrapTemplate uses `prev_message` as key in `$defaultOptions`, but `DefaultTemplate` uses `previous_message`.

**Comment by celucatti** [comment]
Solved.

**Comment by sampart** [comment]
To clarify, this is fixed in https://github.com/whiteoctober/Pagerfanta/pull/230
