### ISSUE TITLE
Use with AJAX

### ISSUE THREAD

**Issue by linnett** [whiteoctober/Pagerfanta#192]
Is it possible to use this with an AJAX solution? I need to update the paging dynamically

**Comment by deepakmahajan00** [comment]
I have a same question. In current pagination provided from pagerfanta is linked based. When we click on link it refresh complete page. I want, it should also ajax based call/request. When I click on pagination link, this call should be ajax based.

**Comment by richsage** [comment]
Yes, this is possible.

You should be able to create a server-side action within your application that, when requested via ajax with the relevant parameters (page number, page size and similar), renders your pagerfanta object as a standalone piece of HTML and returns it to your browser. This can then replace your existing pagerfanta content within your page.

Remember - you only need to render the pagerfanta object itself :-)

**Comment by richsage** [comment]
Closing as this is not an issue with the library itself but rather a question about usage.
