### ISSUE TITLE
Send the query url params to PagerFanta, so links to pages will include them

### ISSUE THREAD

**Issue by arcovoltaico** [whiteoctober/Pagerfanta#193]
I'd like to send the query url params to PagerFanta, so links to pages will include them.

My url http://ds/es/search?district%5B0%5D=12&district%5B1%5D=8/2

My route:
search:
    path:  /{_locale}/search/{page}
    defaults: { _controller: AppBundle:Search:search,page:1 }
    requirements:
      _locale: en|es

I'd like to be able of doing this:
   $adapter = new ArrayAdapter($result);
   $pager = new Pagerfanta($adapter);
    $pager->setQuery( $request->query);

So the url will be 
 http://ds/es/search/2?district%5B0%5D=12&district%5B1%5D=8/2

instead of 
url http://ds/es/search/2   that is not restricting my search result

Hope that you understand my point and  support query params without hacking your nice bundle.
Thanks!!

**Comment by arcovoltaico** [comment]
After a few hours, I don't know how, but I solved it ;-)

**Comment by johnpancoast** [comment]
@arcovoltaico do you have any details on what you did? It seems that pagerfanta only allows you to generate a route for a page without taking into account existing query string params you might want to include in the links.

**Comment by johnpancoast** [comment]
Ah, I just realized that I can have my own `View::render()` method and do `use` for the route generator so that it can get those other params.
