### ISSUE TITLE
How to get the entity class, that is being paged

### ISSUE THREAD

**Issue by pdias** [whiteoctober/Pagerfanta#197]
I need help, i whant to know the entity class that is being paged.

I get a Pagerfanta\Pagerfanta object and from this object i need to know the class of objects that are being paged.

Can someone help me?

Thanks in advance.

Paulo Dias

**Comment by johnpancoast** [comment]
@pdias I was talking on another issue and noticed this so figured I'd respond.

Pagerfanta works with many adapters. Not all of them work with an entity (for example, you can just work with arrays too) so getting the entity is out of scope of what pagerfanta provides.

You probably want to create a custom wrapper class that wraps (or creates, or accepts) your pagerfanta object and has your own getEntity() method.
