### ISSUE TITLE
Page "3" does not exist. The currentPage must be inferior to "1"

### ISSUE THREAD

**Issue by hushulin** [whiteoctober/Pagerfanta#200]
Page "3" does not exist. The currentPage must be inferior to "1"

but , my page 3 have datas

**Comment by hushulin** [comment]
I find this problem : setMaxPerPage() method 's param can not set inferior to 10

**Comment by ihsanudin** [comment]
@hushulin : yes, you need setMaxPerPage minimum 10

**Comment by hushulin** [comment]
@ihsanudin ok,I get it! thanks
