### ISSUE TITLE
integrate with existing code

### ISSUE THREAD

**Issue by ambicoder** [whiteoctober/Pagerfanta#203]
I am trying to find how Pagerfanta would integrate with existing custom code such as mine.For example in a page an SQL query runs and brings all the posts from the database.

How pagerfanta can play a role in the above scenario.

I am just trying to figure out how to "mess" my custom code with Pagerfanta.

DO I have to use Symphony in order for Pagerfanta to work?

**Comment by stof** [comment]
no, you don't have to use Symfony. there is nothing related to Symfony in this library.
And the examples in the readme don't include anything requiring Symfony: https://github.com/whiteoctober/Pagerfanta#readme
