### ISSUE TITLE
sortable

### ISSUE THREAD

**Issue by imsheng** [whiteoctober/Pagerfanta#215]
like the knp-paginator-bundle sortable ?

**Comment by stof** [comment]
making things sortable is totally unrelated to paginating things. So IMO, it does not belong to the same library.

**Comment by richsage** [comment]
Agree with @stof - sorting is separate (whether done through a database query, sorting array prior to paginating or whatever).

**Comment by imsheng** [comment]
Is there sortable library that can be quickly sorted ？
