### ISSUE TITLE
TwitterBootstrapTemplate uses "prev_message" rather than "previous_message"

### ISSUE THREAD

**Issue by sampart** [whiteoctober/Pagerfanta#219]
The [DefaultTemplate](https://github.com/whiteoctober/Pagerfanta/blob/master/src/Pagerfanta/View/Template/DefaultTemplate.php#L20) uses `previous_message` as the option name, but the docs and the other templates (including the [TwitterBootstrapTemplate](https://github.com/whiteoctober/Pagerfanta/blob/master/src/Pagerfanta/View/Template/TwitterBootstrapTemplate.php#L20)) use `prev_message`.  We should update the default to be `prev_message` too.

**Comment by sampart** [comment]
https://github.com/whiteoctober/Pagerfanta/search?utf8=%E2%9C%93&q=prev_message
https://github.com/whiteoctober/Pagerfanta/blob/master/README.md#defaultview

**Comment by the94air** [comment]
That problem is also in the DefaultTemplate `prev_message` instead of `previous_message` in `Readme.md` file

**Comment by sampart** [comment]
For clarity, this has been fixed by #230.
