### ISSUE TITLE
Mariadb: order on subselect ignored

### ISSUE THREAD

**Issue by Garfield-fr** [whiteoctober/Pagerfanta#235]
Hi,

My records pagination isn't order correctly, because MariaDb ignore the "order by" in subselect.

Information:
https://mariadb.com/kb/en/mariadb/why-is-order-by-in-a-from-subquery-ignored/

Where's possible to patch this ?

Thank's

Bertrand

**Comment by sampart** [comment]
Hi @Garfield-fr, how did you solve or work around this in the end?

**Comment by Garfield-fr** [comment]
I have upgraded the doctrine version. On old version, the bug is present into the class "LimitSubqueryOutputWalker".

**Comment by sampart** [comment]
Thanks for explaining.  I figured that might help someone else in future :smiley:
