### ISSUE TITLE
how to add a custom hydrationMode 

### ISSUE THREAD

**Issue by plesiosaure** [whiteoctober/Pagerfanta#247]
It seems that you can set HydrationMode with magical method setHydrationMode on the query before sending to Paginator (see issue #102)  but not use a custom one :  without pagination, you just need to pass the hydrator as a parameter of getResult() 

So how to add a new field  that is not provided in the raw entities datas returned by the query ?

**Comment by stof** [comment]
So passing the hydration mode to `getResult` allows passing a custom one in the ORM but `setHydrationMode`does not ? This looks weird to me.

**Comment by plesiosaure** [comment]
sorry, it works  with passing the key defined in the config.yml : 

`setHydrationMode('my_custom_hydrator')` 

but not if you use the entity manager as described in the [doctrine doc](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#custom-hydration-modes) : 
```
$em->getConfiguration()->addCustomHydrationMode('CustomHydrator', 'MyProject\Hydrators\CustomHydrator'); 
//this seems to work if you dump entity manager : it is added
 setHydrationMode(''CustomHydrator'); // didn'twork for me
```
