### ISSUE TITLE
how to get default routeGenerator?

### ISSUE THREAD

**Issue by erlangp** [whiteoctober/Pagerfanta#252]

**Comment by sampart** [comment]
Hi @erlangp.  Please could you give a bit more information about what you're trying to do here?  What's the context in which you need this?

There isn't a default generator, but you can use the code here (see "RouteGenerator example") to create one in your code: https://github.com/whiteoctober/Pagerfanta#views.

Hope this helps.  Thanks

**Comment by erlangp** [comment]
thanks sir @sampart
