### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sampart** [whiteoctober/Pagerfanta#278]
Hi,

Sam here, one of the current maintainers of this project.

Given that we no longer use PHP in our active projects, it's becoming harder to give this plugin the time it needs.

Therefore, we're looking for new maintainer(s) for this project.

We'd like any new prospective maintainer to fork this project, and then once that fork has moved forward enough to give us confidence in your ownership, we would link to your fork prominently from the top of the README here, encouraging others to use it instead.

If you're interested, please go ahead and fork (if you haven't already) and start work!  If you've forked and would like others to help you, feel free to reply in this issue with details of your fork.

Please do reply here if you have questions.  Thanks in anticipation.

**Comment by joubertredrat** [comment]
Hi @sampart 

I think that is better to create an organization, move this project to there and add people to help this project,  like I made in @websvnphp. what you think?

**Comment by sampart** [comment]
Thanks for the suggestion, @joubertredrat.  That is a good approach, but I'd like to stick with our original one as I don't have the time to manage a transition of the kind you've outlined.

**Comment by chris2kus31** [comment]
We added this library to our api to pass in the results serialized to our UI, however, it seems like it does not work well with Symfony serializer.  Any idea why?  It’s cause slowness and performance issues.

**Comment by sampart** [comment]
The serializer issue is now being tracked via #281.

**Comment by mbabker** [comment]
I made a decision the other day and forked this repo into my own org and am now using the forked repo inside the Symfony bundle I've been maintaining for a while now.  So feel free to check out https://github.com/BabDev/Pagerfanta and start using it in projects.

**Comment by sampart** [comment]
Thank you so much, @mbabker; that's great! ❤️ 

I've [added a reference](https://github.com/whiteoctober/Pagerfanta/pull/286) to your fork to the top of the README.

**Comment by sampart** [comment]
I'm going to archive this project, and have marked it as abandoned [on Packagist](https://packagist.org/packages/pagerfanta/pagerfanta), with a reference to your project instead.  Thanks again.

**Comment by sampart** [comment]
@mbabker At some point, the `whiteoctober` organisation will be deleted, along with this repo. Before that point, your repo - which is currently a fork of this one - will be updated to become the "root" (parent) repository. There's nothing you need to do - this is just FYI - but do let me know if you have any questions. Thanks again for your maintainership.

**Comment by sampart** [comment]
The root has been updated now. Thanks
