### ISSUE TITLE
Single id is not allowed

### ISSUE THREAD

**Issue by Spriteware** [whiteoctober/Pagerfanta#56]
I'm receiving this exception when trying to get current page results :

> Single id is not allowed on composite primary key in entity Nk\PlayerBundle\Entity\Message_Player 

I need theses 2 **@id** I've in my Entity **@ManyToOne** associations to other Entities.

Can you help me ?

Thanks!

**Comment by mvpatel** [comment]
HI Hope you are well I ma getting same issue now,
I have tried your option for $fetchJoinCollection but still it is not working

My error is bellow,

File:
/var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:424
Message:
Single id is not allowed on composite primary key in entity Application\Entity\Notification
Stack trace:
#0 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(1774): Doctrine\ORM\Mapping\MappingException::singleIdNotAllowedOnCompositePrimaryKey('Application\\Ennt...)
#1 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(628): Doctrine\ORM\Mapping\ClassMetadataInfo->getSingleIdentifierFieldName()
#2 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(174): Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping(Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /var/www/project_name-v2/project_name.local/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#4 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Application\\Ennt...)
#5 /var/www/project_name-v2/project_name.local/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata('Application\\Ennt...)
#6 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(281): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Application\\Ennt...)
#7 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1659): Doctrine\ORM\EntityManager->getClassMetadata('Application\\Ennt...)
#8 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1632): Doctrine\ORM\UnitOfWork->doPersist(Object(Application\Entity\Notification), Array)
#9 /var/www/project_name-v2/project_name.local/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(579): Doctrine\ORM\UnitOfWork->persist(Object(Application\Entity\Notification))
#10 /var/www/project_name-v2/project_name.local/module/Application/src/Application/Service/NotificationService.php(29): Doctrine\ORM\EntityManager->persist(Object(Application\Entity\Notification))
#11 /var/www/project_name-v2/project_name.local/module/Application/src/Application/Provider/Base.php(442): Application\Service\NotificationService->insertNotification(Array, Object(Doctrine\ORM\EntityManager))
#12 /var/www/project_name-v2/project_name.local/module/Application/src/Application/Provider/Base.php(415): Application\Provider\Base->_clientNotification('CAPTURE', '851424793164585...', Array)
#13 /var/www/project_name-v2/project_name.local/module/Application/src/Application/Provider/Adyen.php(48): Application\Provider\Base->_logNotification('CAPTURE', '851424793164585...', Array)
#14 /var/www/project_name-v2/project_name.local/module/ProviderApi/src/ProviderApi/Controller/ApiController.php(100): Application\Provider\Adyen->handleNotification(Array)
#15 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): ProviderApi\Controller\ApiController->notifyAction()
#16 /var/www/project_name-v2/project_name.local/module/ProviderApi/src/ProviderApi/Controller/ApiController.php(89): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 [internal function]: ProviderApi\Controller\ApiController->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(ZF\ContentNegotiation\Request), Object(Zend\Http\PhpEnvironment\Response))
#22 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#23 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#24 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /var/www/project_name-v2/project_name.local/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/project_name-v2/project_name.local/public/index.php(21): Zend\Mvc\Application->run()
#27 {main}

**Comment by pablodip** [comment]
@stof this is a Doctrine issue, right?

**Comment by stof** [comment]
Indeed. It does not even have anything to do with the pagination. It is an issue in the Doctrine mapping (trying to use an entity which has a composite key as part of another composite key is not supported)

**Comment by pablodip** [comment]
Thanks @stof!
