### ISSUE TITLE
DoctrineORMAdapter Left Join & Order By

### ISSUE THREAD

**Issue by joseandrespg** [whiteoctober/Pagerfanta#59]
I don't know if this is a real issue, but I think must tell you.

First, I use Pagerfanta on Symfony 2.0.X.

The best way is an example, I use a query like this:

``` php
$q = $em->createQueryBuilder();
$q->select('a, b, c');
$q->from('AcmeBundle:Aaa','a JOIN a.bbb b LEFT JOIN b.ccc c');
$q->addOrderBy('c.foo', 'ASC');
```

> > I use an "order by" in a field that is aggregate in an "left join".

This cause the result of the query (that search the id's in the getIterator() method) add the "c.foo" field to the select stament, and this miss the distinct of a.id, because now the select stament is "DISTINCT a.id, c.foo" and this must be only "DISTINCT a.id".

The  problem is: id's obtained is a repetition of "a.id" for each "c.foo" distinct element, this break the count of the paginator.

I think the query that search id's will be similar to the query that get the count (except the count function), only where clause's and one field on select stament.

The order by clause is only required in the last query that get the final result (I think).

**Comment by ninsuo** [comment]
Google put me here as a first result after having exceptions when paginating the most simple query (without joins) with an orderBy inside.

```php
        $qb = $this
            ->getManager()
            ->createQueryBuilder()
            ->select('s')
            ->from(Section::class, 's')
            ->orderBy('s.position', 'ASC')
         ;
```

Got the problem solved by putting `false` as second argument of my adapter.

```php
        $pager = new Pagerfanta(
           new DoctrineORMAdapter($qb, false)
        );
```

More info: http://stackoverflow.com/a/34296272/731138
